---
# https://support.ansible.com/hc/en-us/articles/201958037-Reboot-a-server-and-wait-for-it-to-come-back

- name: reboot machine
  sudo: yes
  async: 1
  poll: 0
  ignore_errors: true
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"

- name: wating for server to come back
  sudo: false
  delegate_to: 127.0.0.1
  wait_for:
    host: '{{ inventory_hostname }}'
    state: started
    delay: 30
    timeout: 90
