---
- name: Install nvm
  sudo: no
  git:
    repo: https://github.com/creationix/nvm.git
    version: v0.33.1
    dest: ~/.nvm

- name: Add nvm setup to ~/.bashrc
  sudo: no
  lineinfile:
    dest: ~/.bashrc
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    state: present

  with_items:
    - { regexp: '^# nvm setup', line: '# nvm setup' }
    - { regexp: '^export NVM_DIR', line: 'export NVM_DIR="$HOME/.nvm"' }
    - { regexp: '^\[ -s "\$NVM_DIR', line: '[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"' }

- name: Source .bashrc
  sudo: no
  command: 'bash -lc "source ~/.bashrc"'
