---
- name: confirm consolas has not been installed
  register: consolas_stat
  stat:
    path: /usr/share/fonts/truetype/consolas


- name: add font consolas
  sudo: yes
  copy:
    mode: 0755
    src: ./font_data/consolas
    dest: /usr/share/fonts/truetype/
  when: consolas_stat.stat.exists == false
  notify: reload fonts


- name: confirm notosans has not been installed
  register: notosans_stat
  stat:
    path: /usr/share/fonts/truetype/notosans

- name: add notosans
  sudo: yes
  copy:
    mode: 0755
    src: ./font_data/notosans
    dest: /usr/share/fonts/truetype/
  when: notosans_stat.stat.exists == false
  notify: reload fonts
