---
# @Bug: f will be undefined
#- name: confirm consolas has not been installed
#  stat:
#    path: /usr/share/fonts/truetype/consolas
#  register: f
#  tags: font

- name: add font consolas
  sudo: yes
  copy:
    mode: 0755
    src: ./font_data/consolas
    dest: /usr/share/fonts/truetype/
#  when: f.stat.exists == false
  notify: reload fonts
  tags: font

# @Bug: f will be undefined
#- name: confirm notosans has not been installed
#  stat:
#    path: /usr/share/fonts/truetype/notosans
#  register: f
#  tags: font

- name: add notosans
  sudo: yes
  copy:
    mode: 0755
    src: ./font_data/notosans
    dest: /usr/share/fonts/truetype/
#  when: f.stat.exists == false
  notify: reload fonts
  tags: font
