---
- name: add rule to allow access from subnet (class A)
  sudo: yes
  ufw:
    rule: allow
    src: 10.0.0.0/8

- name: add rule to allow access from subnet (class B)
  sudo: yes
  ufw:
    rule: allow
    src: 172.16.0.0/12

- name: add rule to allow access from subnet (class C)
  sudo: yes
  ufw:
    rule: allow
    src: 192.168.0.0/16

- name: configure default settings
  sudo: yes
  ufw: 'direction={{ item.direction }} policy={{ item.policy }}'
  with_items:
    - { direction: 'incoming', policy: 'deny' }
    - { direction: 'outgoing', policy: 'allow' }
    - { direction: 'routed', policy: 'deny' }

- name: enable logging
  sudo: yes
  ufw:
    logging: on

- name: enable uwf
  sudo: yes
  ufw:
    state: enabled

- name: restart uwf
  sudo: yes
  service:
    name: ufw
    state: restarted
